# Generated by Django 4.1.5 on 2023-01-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                default="product_images/default.png", upload_to="product_images/"
            ),
        ),
    ]
